tasks:
  - name: Setup environment and PHP/Composer dependencies
    openMode: split-left
    init: |
      cp .env.example .env &&
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8000)#g" .env
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env
      composer install --ignore-platform-reqs
      gp sync-done composer-deps
      php artisan key:generate
      php artisan storage:link
      php artisan serve

  - name: Install Node dependencies and run Vite
    openMode: split-right
    command: |
      npm install
      npm run dev

  - name: Start DB
    openMode: split-right
    command: |
      touch database/database.sqlite
      gp sync-await composer-deps
      php artisan migrate:fresh --seed

ports:
  - port: 5173
    onOpen: ignore
    visibility: public
    name: Node Server for Vite

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
